auth_enabled: false

server:
  http_listen_port: 3100

ui:
  enabled: true

ruler:
  alertmanager_url: alertmanager:9093

common:
  path_prefix: /var/lib/loki/data
  replication_factor: 1
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/data/chunks
      rules_directory: /var/lib/loki/data/rules
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2026-09-28
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        path_prefix: index/
        prefix: loki-index-table
        period: 24h
      chunks:
        prefix: loki-chunks-table

limits_config:
  retention_period: 7d
  ingestion_rate_strategy: 'local'
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6
  max_streams_per_user: 10000
  max_line_size: 256000

compactor:
  working_directory: /var/lib/loki/data/retention
  compaction_interval: 10m # dictates how often compaction is applied. If the Compactor falls behind, compaction occurs as soon as possible.
  retention_enabled: true # Without this, the Compactor will only compact tables
  retention_delete_delay: 2h # the delay after which the Compactor will delete marked chunks.
  retention_delete_worker_count: 150 # specifies the maximum quantity of goroutine workers instantiated to delete chunks.
  delete_request_store: filesystem # configure the store for delete requests. This is required when retention is enabled.
